MujocoPlugins:
  - type: mujoco_contact_surfaces/MujocoContactSurfacesPlugin
    SurfacePlugins:
      - {
          type: mujoco_contact_surface_sensors/TaxelSensor,
          sensorName: "myrmex_sensor0",
          geomName: "myrmex_foam",
          topicName: "/tactile_module_16x16_v2",
          updateRate: 50.0,
          visualize: True,
          include_margin: 0.00016044444444444426,
          method: "weighted",
          sample_resolution: 0.01,
          taxels:
            [
              [-0.19, -0.19, 0.02],
              [-0.19, -0.16466666666666668, 0.02],
              [-0.19, -0.13933333333333334, 0.02],
              [-0.19, -0.114, 0.02],
              [-0.19, -0.08866666666666667, 0.02],
              [-0.19, -0.06333333333333335, 0.02],
              [-0.19, -0.038000000000000006, 0.02],
              [-0.19, -0.01266666666666666, 0.02],
              [-0.19, 0.01266666666666666, 0.02],
              [-0.19, 0.03799999999999998, 0.02],
              [-0.19, 0.0633333333333333, 0.02],
              [-0.19, 0.08866666666666667, 0.02],
              [-0.19, 0.11399999999999999, 0.02],
              [-0.19, 0.1393333333333333, 0.02],
              [-0.19, 0.16466666666666668, 0.02],
              [-0.19, 0.19, 0.02],
              [-0.16466666666666668, -0.19, 0.02],
              [-0.16466666666666668, -0.16466666666666668, 0.02],
              [-0.16466666666666668, -0.13933333333333334, 0.02],
              [-0.16466666666666668, -0.114, 0.02],
              [-0.16466666666666668, -0.08866666666666667, 0.02],
              [-0.16466666666666668, -0.06333333333333335, 0.02],
              [-0.16466666666666668, -0.038000000000000006, 0.02],
              [-0.16466666666666668, -0.01266666666666666, 0.02],
              [-0.16466666666666668, 0.01266666666666666, 0.02],
              [-0.16466666666666668, 0.03799999999999998, 0.02],
              [-0.16466666666666668, 0.0633333333333333, 0.02],
              [-0.16466666666666668, 0.08866666666666667, 0.02],
              [-0.16466666666666668, 0.11399999999999999, 0.02],
              [-0.16466666666666668, 0.1393333333333333, 0.02],
              [-0.16466666666666668, 0.16466666666666668, 0.02],
              [-0.16466666666666668, 0.19, 0.02],
              [-0.13933333333333334, -0.19, 0.02],
              [-0.13933333333333334, -0.16466666666666668, 0.02],
              [-0.13933333333333334, -0.13933333333333334, 0.02],
              [-0.13933333333333334, -0.114, 0.02],
              [-0.13933333333333334, -0.08866666666666667, 0.02],
              [-0.13933333333333334, -0.06333333333333335, 0.02],
              [-0.13933333333333334, -0.038000000000000006, 0.02],
              [-0.13933333333333334, -0.01266666666666666, 0.02],
              [-0.13933333333333334, 0.01266666666666666, 0.02],
              [-0.13933333333333334, 0.03799999999999998, 0.02],
              [-0.13933333333333334, 0.0633333333333333, 0.02],
              [-0.13933333333333334, 0.08866666666666667, 0.02],
              [-0.13933333333333334, 0.11399999999999999, 0.02],
              [-0.13933333333333334, 0.1393333333333333, 0.02],
              [-0.13933333333333334, 0.16466666666666668, 0.02],
              [-0.13933333333333334, 0.19, 0.02],
              [-0.114, -0.19, 0.02],
              [-0.114, -0.16466666666666668, 0.02],
              [-0.114, -0.13933333333333334, 0.02],
              [-0.114, -0.114, 0.02],
              [-0.114, -0.08866666666666667, 0.02],
              [-0.114, -0.06333333333333335, 0.02],
              [-0.114, -0.038000000000000006, 0.02],
              [-0.114, -0.01266666666666666, 0.02],
              [-0.114, 0.01266666666666666, 0.02],
              [-0.114, 0.03799999999999998, 0.02],
              [-0.114, 0.0633333333333333, 0.02],
              [-0.114, 0.08866666666666667, 0.02],
              [-0.114, 0.11399999999999999, 0.02],
              [-0.114, 0.1393333333333333, 0.02],
              [-0.114, 0.16466666666666668, 0.02],
              [-0.114, 0.19, 0.02],
              [-0.08866666666666667, -0.19, 0.02],
              [-0.08866666666666667, -0.16466666666666668, 0.02],
              [-0.08866666666666667, -0.13933333333333334, 0.02],
              [-0.08866666666666667, -0.114, 0.02],
              [-0.08866666666666667, -0.08866666666666667, 0.02],
              [-0.08866666666666667, -0.06333333333333335, 0.02],
              [-0.08866666666666667, -0.038000000000000006, 0.02],
              [-0.08866666666666667, -0.01266666666666666, 0.02],
              [-0.08866666666666667, 0.01266666666666666, 0.02],
              [-0.08866666666666667, 0.03799999999999998, 0.02],
              [-0.08866666666666667, 0.0633333333333333, 0.02],
              [-0.08866666666666667, 0.08866666666666667, 0.02],
              [-0.08866666666666667, 0.11399999999999999, 0.02],
              [-0.08866666666666667, 0.1393333333333333, 0.02],
              [-0.08866666666666667, 0.16466666666666668, 0.02],
              [-0.08866666666666667, 0.19, 0.02],
              [-0.06333333333333335, -0.19, 0.02],
              [-0.06333333333333335, -0.16466666666666668, 0.02],
              [-0.06333333333333335, -0.13933333333333334, 0.02],
              [-0.06333333333333335, -0.114, 0.02],
              [-0.06333333333333335, -0.08866666666666667, 0.02],
              [-0.06333333333333335, -0.06333333333333335, 0.02],
              [-0.06333333333333335, -0.038000000000000006, 0.02],
              [-0.06333333333333335, -0.01266666666666666, 0.02],
              [-0.06333333333333335, 0.01266666666666666, 0.02],
              [-0.06333333333333335, 0.03799999999999998, 0.02],
              [-0.06333333333333335, 0.0633333333333333, 0.02],
              [-0.06333333333333335, 0.08866666666666667, 0.02],
              [-0.06333333333333335, 0.11399999999999999, 0.02],
              [-0.06333333333333335, 0.1393333333333333, 0.02],
              [-0.06333333333333335, 0.16466666666666668, 0.02],
              [-0.06333333333333335, 0.19, 0.02],
              [-0.038000000000000006, -0.19, 0.02],
              [-0.038000000000000006, -0.16466666666666668, 0.02],
              [-0.038000000000000006, -0.13933333333333334, 0.02],
              [-0.038000000000000006, -0.114, 0.02],
              [-0.038000000000000006, -0.08866666666666667, 0.02],
              [-0.038000000000000006, -0.06333333333333335, 0.02],
              [-0.038000000000000006, -0.038000000000000006, 0.02],
              [-0.038000000000000006, -0.01266666666666666, 0.02],
              [-0.038000000000000006, 0.01266666666666666, 0.02],
              [-0.038000000000000006, 0.03799999999999998, 0.02],
              [-0.038000000000000006, 0.0633333333333333, 0.02],
              [-0.038000000000000006, 0.08866666666666667, 0.02],
              [-0.038000000000000006, 0.11399999999999999, 0.02],
              [-0.038000000000000006, 0.1393333333333333, 0.02],
              [-0.038000000000000006, 0.16466666666666668, 0.02],
              [-0.038000000000000006, 0.19, 0.02],
              [-0.01266666666666666, -0.19, 0.02],
              [-0.01266666666666666, -0.16466666666666668, 0.02],
              [-0.01266666666666666, -0.13933333333333334, 0.02],
              [-0.01266666666666666, -0.114, 0.02],
              [-0.01266666666666666, -0.08866666666666667, 0.02],
              [-0.01266666666666666, -0.06333333333333335, 0.02],
              [-0.01266666666666666, -0.038000000000000006, 0.02],
              [-0.01266666666666666, -0.01266666666666666, 0.02],
              [-0.01266666666666666, 0.01266666666666666, 0.02],
              [-0.01266666666666666, 0.03799999999999998, 0.02],
              [-0.01266666666666666, 0.0633333333333333, 0.02],
              [-0.01266666666666666, 0.08866666666666667, 0.02],
              [-0.01266666666666666, 0.11399999999999999, 0.02],
              [-0.01266666666666666, 0.1393333333333333, 0.02],
              [-0.01266666666666666, 0.16466666666666668, 0.02],
              [-0.01266666666666666, 0.19, 0.02],
              [0.01266666666666666, -0.19, 0.02],
              [0.01266666666666666, -0.16466666666666668, 0.02],
              [0.01266666666666666, -0.13933333333333334, 0.02],
              [0.01266666666666666, -0.114, 0.02],
              [0.01266666666666666, -0.08866666666666667, 0.02],
              [0.01266666666666666, -0.06333333333333335, 0.02],
              [0.01266666666666666, -0.038000000000000006, 0.02],
              [0.01266666666666666, -0.01266666666666666, 0.02],
              [0.01266666666666666, 0.01266666666666666, 0.02],
              [0.01266666666666666, 0.03799999999999998, 0.02],
              [0.01266666666666666, 0.0633333333333333, 0.02],
              [0.01266666666666666, 0.08866666666666667, 0.02],
              [0.01266666666666666, 0.11399999999999999, 0.02],
              [0.01266666666666666, 0.1393333333333333, 0.02],
              [0.01266666666666666, 0.16466666666666668, 0.02],
              [0.01266666666666666, 0.19, 0.02],
              [0.03799999999999998, -0.19, 0.02],
              [0.03799999999999998, -0.16466666666666668, 0.02],
              [0.03799999999999998, -0.13933333333333334, 0.02],
              [0.03799999999999998, -0.114, 0.02],
              [0.03799999999999998, -0.08866666666666667, 0.02],
              [0.03799999999999998, -0.06333333333333335, 0.02],
              [0.03799999999999998, -0.038000000000000006, 0.02],
              [0.03799999999999998, -0.01266666666666666, 0.02],
              [0.03799999999999998, 0.01266666666666666, 0.02],
              [0.03799999999999998, 0.03799999999999998, 0.02],
              [0.03799999999999998, 0.0633333333333333, 0.02],
              [0.03799999999999998, 0.08866666666666667, 0.02],
              [0.03799999999999998, 0.11399999999999999, 0.02],
              [0.03799999999999998, 0.1393333333333333, 0.02],
              [0.03799999999999998, 0.16466666666666668, 0.02],
              [0.03799999999999998, 0.19, 0.02],
              [0.0633333333333333, -0.19, 0.02],
              [0.0633333333333333, -0.16466666666666668, 0.02],
              [0.0633333333333333, -0.13933333333333334, 0.02],
              [0.0633333333333333, -0.114, 0.02],
              [0.0633333333333333, -0.08866666666666667, 0.02],
              [0.0633333333333333, -0.06333333333333335, 0.02],
              [0.0633333333333333, -0.038000000000000006, 0.02],
              [0.0633333333333333, -0.01266666666666666, 0.02],
              [0.0633333333333333, 0.01266666666666666, 0.02],
              [0.0633333333333333, 0.03799999999999998, 0.02],
              [0.0633333333333333, 0.0633333333333333, 0.02],
              [0.0633333333333333, 0.08866666666666667, 0.02],
              [0.0633333333333333, 0.11399999999999999, 0.02],
              [0.0633333333333333, 0.1393333333333333, 0.02],
              [0.0633333333333333, 0.16466666666666668, 0.02],
              [0.0633333333333333, 0.19, 0.02],
              [0.08866666666666667, -0.19, 0.02],
              [0.08866666666666667, -0.16466666666666668, 0.02],
              [0.08866666666666667, -0.13933333333333334, 0.02],
              [0.08866666666666667, -0.114, 0.02],
              [0.08866666666666667, -0.08866666666666667, 0.02],
              [0.08866666666666667, -0.06333333333333335, 0.02],
              [0.08866666666666667, -0.038000000000000006, 0.02],
              [0.08866666666666667, -0.01266666666666666, 0.02],
              [0.08866666666666667, 0.01266666666666666, 0.02],
              [0.08866666666666667, 0.03799999999999998, 0.02],
              [0.08866666666666667, 0.0633333333333333, 0.02],
              [0.08866666666666667, 0.08866666666666667, 0.02],
              [0.08866666666666667, 0.11399999999999999, 0.02],
              [0.08866666666666667, 0.1393333333333333, 0.02],
              [0.08866666666666667, 0.16466666666666668, 0.02],
              [0.08866666666666667, 0.19, 0.02],
              [0.11399999999999999, -0.19, 0.02],
              [0.11399999999999999, -0.16466666666666668, 0.02],
              [0.11399999999999999, -0.13933333333333334, 0.02],
              [0.11399999999999999, -0.114, 0.02],
              [0.11399999999999999, -0.08866666666666667, 0.02],
              [0.11399999999999999, -0.06333333333333335, 0.02],
              [0.11399999999999999, -0.038000000000000006, 0.02],
              [0.11399999999999999, -0.01266666666666666, 0.02],
              [0.11399999999999999, 0.01266666666666666, 0.02],
              [0.11399999999999999, 0.03799999999999998, 0.02],
              [0.11399999999999999, 0.0633333333333333, 0.02],
              [0.11399999999999999, 0.08866666666666667, 0.02],
              [0.11399999999999999, 0.11399999999999999, 0.02],
              [0.11399999999999999, 0.1393333333333333, 0.02],
              [0.11399999999999999, 0.16466666666666668, 0.02],
              [0.11399999999999999, 0.19, 0.02],
              [0.1393333333333333, -0.19, 0.02],
              [0.1393333333333333, -0.16466666666666668, 0.02],
              [0.1393333333333333, -0.13933333333333334, 0.02],
              [0.1393333333333333, -0.114, 0.02],
              [0.1393333333333333, -0.08866666666666667, 0.02],
              [0.1393333333333333, -0.06333333333333335, 0.02],
              [0.1393333333333333, -0.038000000000000006, 0.02],
              [0.1393333333333333, -0.01266666666666666, 0.02],
              [0.1393333333333333, 0.01266666666666666, 0.02],
              [0.1393333333333333, 0.03799999999999998, 0.02],
              [0.1393333333333333, 0.0633333333333333, 0.02],
              [0.1393333333333333, 0.08866666666666667, 0.02],
              [0.1393333333333333, 0.11399999999999999, 0.02],
              [0.1393333333333333, 0.1393333333333333, 0.02],
              [0.1393333333333333, 0.16466666666666668, 0.02],
              [0.1393333333333333, 0.19, 0.02],
              [0.16466666666666668, -0.19, 0.02],
              [0.16466666666666668, -0.16466666666666668, 0.02],
              [0.16466666666666668, -0.13933333333333334, 0.02],
              [0.16466666666666668, -0.114, 0.02],
              [0.16466666666666668, -0.08866666666666667, 0.02],
              [0.16466666666666668, -0.06333333333333335, 0.02],
              [0.16466666666666668, -0.038000000000000006, 0.02],
              [0.16466666666666668, -0.01266666666666666, 0.02],
              [0.16466666666666668, 0.01266666666666666, 0.02],
              [0.16466666666666668, 0.03799999999999998, 0.02],
              [0.16466666666666668, 0.0633333333333333, 0.02],
              [0.16466666666666668, 0.08866666666666667, 0.02],
              [0.16466666666666668, 0.11399999999999999, 0.02],
              [0.16466666666666668, 0.1393333333333333, 0.02],
              [0.16466666666666668, 0.16466666666666668, 0.02],
              [0.16466666666666668, 0.19, 0.02],
              [0.19, -0.19, 0.02],
              [0.19, -0.16466666666666668, 0.02],
              [0.19, -0.13933333333333334, 0.02],
              [0.19, -0.114, 0.02],
              [0.19, -0.08866666666666667, 0.02],
              [0.19, -0.06333333333333335, 0.02],
              [0.19, -0.038000000000000006, 0.02],
              [0.19, -0.01266666666666666, 0.02],
              [0.19, 0.01266666666666666, 0.02],
              [0.19, 0.03799999999999998, 0.02],
              [0.19, 0.0633333333333333, 0.02],
              [0.19, 0.08866666666666667, 0.02],
              [0.19, 0.11399999999999999, 0.02],
              [0.19, 0.1393333333333333, 0.02],
              [0.19, 0.16466666666666668, 0.02],
              [0.19, 0.19, 0.02],
            ],
        }
